Project.MVCUI/Controllers/ShoppingController.cs
using PagedList;
using Project.BLL.Repositories.ConcRep;
using Project.ENTITIES.Enums;
using Project.MVCUI.Models.ShoppingTools;
using Project.VM.PureVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using Project.ENTITIES.Models;
using Project.MVCUI.Models.PageVMs;
using System.Web.Management;
using System.Net.Http;
using System.Threading.Tasks;
using Project.COMMON.Tools;
using System.ComponentModel.DataAnnotations;

namespace Project.MVCUI.Controllers
{
    public class ShoppingController : Controller
    {
        OrderRepository _ordRep;
        ProductRepository _prodRep;
        CategoryRepository _catRep;
        OrderDetailRepository _ordDetRep;
        public ShoppingController()
        {
            _prodRep = new ProductRepository();
            _ordDetRep = new OrderDetailRepository();
            _catRep = new CategoryRepository();
            _ordRep = new OrderRepository();
        }

        public ActionResult ShoppingList(int? page, int? categoryID)
        {
            IPagedList<ProductVM> products = categoryID == null ? _prodRep.Where(x => x.Status != ENTITIES.Enums.DataStatus.Deleted).Select(x => new ProductVM
            {
                ID = x.ID,
                ProductName = x.ProductName,
                UnitPrice = x.UnitPrice,
                UnitsInStock = x.UnitsInStock,
                CategoryName = x.Category != null ? x.Category.CategoryName : "",
                ImagePath = x.ImagePath,
                Status = x.Status.ToString(),

            }).ToPagedList(page ?? 1, 9) : _prodRep.Where(x => x.CategoryID == categoryID && x.Status != ENTITIES.Enums.DataStatus.Deleted).Select(x => new ProductVM
            {
                ID = x.ID,
                ProductName = x.ProductName,
                UnitPrice = x.UnitPrice,
                UnitsInStock = x.UnitsInStock,
                CategoryName = x.Category != null ? x.Category.CategoryName : "",
                ImagePath = x.ImagePath,
                CategoryID = x.CategoryID,
                Status = x.Status.ToString(),


            }).ToPagedList(page ?? 1, 9);

            PaginationVM pavm = new PaginationVM
            {
                PagedProducts = products,

                Categories = _catRep.Select(x => new CategoryVM
                {
                    ID = x.ID,
                    CategoryName = x.CategoryName,
                    Description = x.Description,
                }).ToList()
            };


            if (categoryID != null)
            {
                TempData["catID"] = categoryID;
            }

            return View(pavm);
        }

        [HandleError(View ="Stok Bitti")]

       
        public ActionResult AddToCart(int id)
        {
            Cart c = Session["scart"] == null ? new Cart() : Session["scart"] as Cart;

            Product add = _prodRep.Find(id);

            CartItem ci = new CartItem
            {
                ID = add.ID,
                Name = add.ProductName,
                Price = add.UnitPrice,
                ImagePath = add.ImagePath,
            };
            foreach (CartItem item in c.Sepetim)
            {
                if (add.UnitsInStock - item.Amount <=0)
                {
                    TempData["outOfStockMessage"] = "Üzgünüz, Bu ürün üçün stok yeterlı değildir";
                    return Redirect(Request.UrlReferrer.ToString());

                }
            }
        
          
         
           

            c.SepeteEkle(ci);
            Session["scart"] = c;

            //return RedirectToAction("ShoppingList");

            return Redirect(Request.UrlReferrer.ToString());

        }

        public ActionResult CartPage()
        {
            if (Session["scart"] != null)
            {
                Cart c = Session["scart"] as Cart;
                CartPageVM cpvm = new CartPageVM
                {
                    Cart = c,
                };
                return View(cpvm);
            }
            ViewBag.SepetBos = "Sepetinizde Ürün Bulunamamktadır";
            return RedirectToAction("ShoppingList");
        }

        public ActionResult DeleteFromCart(int id)
        {
            if (Session["scart"] != null)
            {
                Cart c = Session["scart"] as Cart;
                c.SepettenCikar(id);
                if (c.Sepetim.Count == 0)
                {
                    Session.Remove("scart");
                    TempData["sepetBos"] = "Sepetnizdeki Tüm Ürünler Çıkarılmıştır";
                    return RedirectToAction("ShoppingList");
                }
            }
            return RedirectToAction("CartPage");
        }

        public ActionResult ConfirmOrder()
        {
            AppUser currentUser;
            if (Session["member"] != null)
            {
                currentUser = Session["member"] as AppUser;
            }

            return View();
        }
        //http://localhost:58476/api/Payment/ReceivePayment
        //PaymentRequestModel

        [HttpPost]
        public ActionResult ConfirmOrder(OrderPageVM ovm)
        {
            bool sonuc;
            Cart sepet = Session["scart"] as Cart;
            ovm.Order.TotalPrice = ovm.PaymentRM.ShoppingPrice = sepet.TotalPrice;

            #region APISection
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:58476/api/");
                Task<HttpResponseMessage> postTask = client.PostAsJsonAsync("Payment/ReceivePayment", ovm.PaymentRM);

                HttpResponseMessage result;
                try
                {
                    result = postTask.Result;
                }
                catch (Exception ex)
                {
                    TempData["baglantiRed"] = "Banka baglantıyı reddetti";
                    return RedirectToAction("ShoppingList");
                }

                if (result.IsSuccessStatusCode) sonuc = true;
                else sonuc = false;

                if (sonuc)
                {
                    if (Session["member"] != null)
                    {
                        AppUser kullanici = Session["member"] as AppUser;
                        ovm.Order.AppUserID = kullanici.ID;

                    }

                    _ordRep.Add(ovm.Order); //OrderRepository bu noktada Order'i eklerken onun ID'sini olusturur...

                    foreach (CartItem item in sepet.Sepetim)
                    {
                        OrderDetail od = new OrderDetail();
                        od.OrderID = ovm.Order.ID;
                        od.ProductID = item.ID;
                        od.TotalPrice = item.SubTotal;
                        od.Quantity = item.Amount;
                        _ordDetRep.Add(od);

                        //Stoktan da düsürelim
                        Product stoktanDusurulecek = _prodRep.Find(item.ID);
                        stoktanDusurulecek.UnitsInStock -= item.Amount;

                        _prodRep.Update(stoktanDusurulecek);

                        //Algoritma  Ödevi : Eger stoktan düsürüldügünde stokta kalmayacak bir şekilde item varsa onun Amount'ı Sepette asılamayacak bir hale gelsin

                    }


                    TempData["odeme"] = "Siparişiniz bize ulasmıstır...Tesekkür ederiz";

                    if (Session["member"] != null)
                        MailService.Send(ovm.Order.AppUser.Email, body: $"Siparişiniz basarıyla alındı{ovm.Order.TotalPrice}"); //Kullanıcıya aldıgı ürünleri de Mail yoluyla gönderin...
                    else MailService.Send(ovm.Order.NonMemberEmail, body: $"Siparişiniz basarıyla alındı{ovm.Order.TotalPrice}");

                    Session.Remove("scart");
                    return RedirectToAction("ShoppingList");
                }

                else
                {
                    Task<string> s = result.Content.ReadAsStringAsync();
                    TempData["sorun"] = s;
                    return RedirectToAction("ShoppingList");
                }

            }



            #endregion
        }

    }
}

Project.MVCUI/Views/Shopping/CartPage.cshtml
@model CartPageVM
@{
    ViewBag.Title = "CartPage";
}

<div class="jumbotron">
    Odemeniz gereken toplam tutar => @Model.Cart.TotalPrice ... Siparişi onaylamak icin lütfen @Html.ActionLink("tıklayınız", "ConfirmOrder")
</div>



<div class="row product-list">

    @foreach (CartItem item in Model.Cart.Sepetim)
    {

        <div class="col-md-4">
            <section class="panel">
                <div class="pro-img-box">
                    @if (item.ImagePath == null || item.ImagePath == "3" || item.ImagePath == "2" || item.ImagePath.Contains("nightlife"))
                    {
                        <img src="~/Pictures/gg.jpg" alt="Resim yok" width="100" height="300" title="@item.Name" />
                    }
                    else
                    {
                        <img src="@item.ImagePath" alt="Resim yok" width="100" height="300" title="@item.Name" />
                    }

                    <a href="@Url.Action("DeleteFromCart", new { id=item.ID})" class="adtocart">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>
                </div>

                <div class="panel-body text-center">
                    <h4>
                        <a href="#" class="pro-title" title="@item.Name">
                            @item.Name x @item.Amount
                        </a>
                    </h4>
                    <p class="price"> @item.SubTotal</p>
                </div>

            </section>
        </div>

    }






</div>

Project.MVCUI/Views/Shopping/ConfirmOrder.cshtml
@model OrderPageVM
@{
    ViewBag.Title = "ConfirmOrder";
}

<div>

    @using (Html.BeginForm())
    {

        <div class="form-group">
            <label class="col-sm-2 control-label">Gönderim Adresi</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.Order.ShippingAddress, new { @class = "form-control" })
            </div>

        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Kart Numarası</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentRM.CardNumber, new { @class = "form-control" })
            </div>

        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Kart Güvenlik Numarası </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentRM.SecurityNumber, new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Geçerlilik Süresi </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentRM.CardExpiryYear, new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Geçerlilik Süresi(Ay) </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentRM.CardExpiryMonth, new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Kart Üzerindeki İsim </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentRM.CardUserName, new { @class = "form-control" })

            </div>
        </div>

        if (Session["member"] == null)
        {
            <div class="form-group">
                <label class="col-sm-2 control-label">Email </label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.Order.NonMemberEmail, new { @class = "form-control" })

                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">İsim SoyIsim </label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.Order.NonMemberName, new { @class = "form-control" })

                </div>
            </div>

        }
        <div class="form-group">
            <label class="col-sm-2 control-label">Onaylamak İçin Tıklayınız</label>
            <div class="col-sm-10">
                <button class="btn btn-primary">Onayla</button>

            </div>
        </div>


    }



</div>

Project.MVCUI/Views/Shopping/ShoppingList.cshtml
@model PaginationVM
@{
    ViewBag.Title = "ShoppingList";
}




<h2 style="background-color:red">@TempData["sepetBos"]</h2>
<h1>@TempData["outOfStockMessage"]</h1>
@TempData["baglantiRed"]
@TempData["odeme"]
@TempData["sorun"]
<section class="wrapper">
    <!-- page start-->
    <div class="row">
        <div class="col-md-3">





            <section class="panel">
                <header class="panel-heading">
                    Category
                </header>
                <div class="panel-body">
                    <ul class="nav prod-cat">
                        @foreach (CategoryVM item in Model.Categories)
                        {

                            <li style="padding-top:30px">  @Html.ActionLink(item.CategoryName, "ShoppingList", new { categoryID = item.ID }, new { @class = "btn btn-primary" })    </li>
                        }
                    </ul>
                </div>
            </section>

        </div>
        <div class="col-md-9">
            <section class="panel">
                <div class="panel-body">


                    <div class="pull-right">
                        <ul class="pagination pagination-sm pro-page-list">

                            @if (TempData["catID"] != null)
                            {
                                <li> @Html.PagedListPager(Model.PagedProducts, page => Url.Action("ShoppingList", new { page, categoryID = TempData["catID"] }))     </li>
                            }
                            else
                            {
                                <li>
                                    @Html.PagedListPager(Model.PagedProducts, page => Url.Action("ShoppingList", new { page }))
                                </li>
                            }


                        </ul>
                    </div>
                </div>
            </section>

            <div class="row product-list">


                @foreach (ProductVM item in Model.PagedProducts)
                {

                    <div class="col-md-4">
                        <section class="panel">
                            <div class="pro-img-box">

                                @if (item.ImagePath == null || item.ImagePath == "3" || item.ImagePath == "2" || item.ImagePath.Contains("nightlife"))
                                {
                                    <img src="~/Pictures/gg.jpg" alt="Resim yok" width="100" height="300" title="@item.ProductName" />
                                }
                                else
                                {
                                    <img src="@item.ImagePath" alt="Resim yok" width="100" height="300" title="@item.ProductName" />
                                }
                                @*

                                    Url.Action'in bize verdigi fayda,asagıdaki gibi belli durumlarda ActionLink kullanmak tasarımımıza uygun olmayabilir...


                                *@


                                <a href="@Url.Action("AddToCart", new {id=item.ID})" class="adtocart">
                                    <i class="icon-shopping-cart"></i>
                                </a>
                            </div>

                            <div class="panel-body text-center">
                                <h4>
                                    <a href="#" class="pro-title" title="@item.ProductName">
                                        @item.ProductName
                                    </a>
                                </h4>
                                <p class="price">$@item.UnitPrice</p>
                            </div>
                        </section>
                    </div>
                }



            </div>
        </div>
    </div>
    <!-- page end-->
</section>

@section Sepet{

    <li>
        <a href="@Url.Action("CartPage","Shopping")"> <i class="icon-shopping-cart"></i>  Cart </a>
    </li>

}
<div id="uyari" style="display: none;">Ürün stokta yok!</div>